spring.application.name=vitalsy-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/vitalsy_db
spring.datasource.username=postgres
spring.datasource.password=psql123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# OpenAI
# Configuración para conectar con tu LM Studio local [cite: 116, 136]
spring.ai.openai.base-url=http://localhost:1234
spring.ai.openai.api-key=vitalsy-local
spring.ai.openai.chat.options.model=google/gemma-4-e2b
# Apaga el open-in-view para evitar warnings 
spring.jpa.open-in-view=false