ALTER TABLE usuarios 
ADD COLUMN IF NOT EXISTS altura DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS tipo_insulina VARCHAR(50),
ADD COLUMN IF NOT EXISTS ratio_ic DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS factor_is DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS alertas_glucosa BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS recordatorio_comidas BOOLEAN DEFAULT FALSE;
